templateDir: ./sdk-resources/resources
packageName: cc
packageVersion: 1.0.3
generateInterfaces: false
enumClassPrefix: false
disallowAdditionalPropertiesIfNotPresent: false
useOneOfDiscriminatorLookup: false