templateDir: ./sdk-resources/resources
packageName: v3
packageVersion: 2.0.0
generateInterfaces: false
disallowAdditionalPropertiesIfNotPresent: false
useOneOfDiscriminatorLookup: false
enumClassPrefix: true
gitRepoId: golang-sdk/v2
gitUserId: sailpoint-oss
